### ISSUE TITLE
Moving bot bug

### ISSUE THREAD

**Issue by EchotheloneMonk** [Lacyway/SAIN#14]
got this error but i dont know why and how

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SAIN.SAINComponent.Classes.Mover.SAINSprint.move (UnityEngine.Vector3 direction) (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
SAIN.SAINComponent.Classes.Mover.SAINSprint+<runPath>d__52.MoveNext () (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ca21460feb9c47d0ac337b9893474cc6>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class410:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SAIN.SAINComponent.Classes.Mover.SAINSprint.move (UnityEngine.Vector3 direction) (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
SAIN.SAINComponent.Classes.Mover.SAINSprint+<runPath>d__52.MoveNext () (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ca21460feb9c47d0ac337b9893474cc6>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class410:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by MacStew27** [comment]
Got this too on RC3

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SAIN.SAINComponent.Classes.Mover.SAINSprint.move (UnityEngine.Vector3 direction) (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
SAIN.SAINComponent.Classes.Mover.SAINSprint+<runPath>d__52.MoveNext () (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ca21460feb9c47d0ac337b9893474cc6>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class410:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SAIN.SAINComponent.Classes.Mover.SAINSprint.move (UnityEngine.Vector3 direction) (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
SAIN.SAINComponent.Classes.Mover.SAINSprint+<runPath>d__52.MoveNext () (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ca21460feb9c47d0ac337b9893474cc6>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class410:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SAIN.SAINComponent.Classes.Mover.SAINSprint.move (UnityEngine.Vector3 direction) (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
SAIN.SAINComponent.Classes.Mover.SAINSprint+<runPath>d__52.MoveNext () (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ca21460feb9c47d0ac337b9893474cc6>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class410:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SAIN.SAINComponent.Classes.Mover.SAINSprint.move (UnityEngine.Vector3 direction) (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
SAIN.SAINComponent.Classes.Mover.SAINSprint+<runPath>d__52.MoveNext () (at <71935ff5a7e14d3bbd2caad7fa7fa144>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ca21460feb9c47d0ac337b9893474cc6>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class410:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Lacyway** [comment]
Should be fixed with https://github.com/Lacyway/SAIN/commit/257cf4c107b98e9a4471e841ecd63f04833f5356
