### ISSUE TITLE
SAIN 3.2.0 RC4

### ISSUE THREAD

**Issue by OrjonV1** [Lacyway/SAIN#16]
1. I have noticed FPS drops and micro clipping

I freshly installed the entire SPT along with the mods WAYPOINT, BIGBRAIN, AND SAIN RC4 from the SVM program I ran the Halloween event with zombies I went to Customs and the first thing I noticed was fps drops zombies are attacking and shooting just these FPS can be annoying I still need to check the behavior of SCAV and PMC

Also adds Logs from a freshly installed SPT

[2024.12.04_16-32-06_0.15.5.1.33420.zip](https://github.com/user-attachments/files/18011616/2024.12.04_16-32-06_0.15.5.1.33420.zip)

[Player.zip](https://github.com/user-attachments/files/18011988/Player.zip)

**Comment by OrjonV1** [comment]
![Zrzut ekranu 2024-12-04 180141](https://github.com/user-attachments/assets/d049c2da-29e5-45a2-ad78-078b3af12dac)
![Zrzut ekranu 2024-12-04 180212](https://github.com/user-attachments/assets/6d7a4cba-9802-4707-ae5b-23876018d9ba)

specifications of my computer
![Zrzut ekranu 2024-12-04 180454](https://github.com/user-attachments/assets/eabe5e1c-5351-436a-8284-7e5b80ddf3e5)

**Comment by Lacyway** [comment]
I have merged my changes to Solarint and will no longer provide support.
