### ISSUE TITLE
trying to help with Sain

### ISSUE THREAD

**Issue by EchotheloneMonk** [Lacyway/SAIN#2]
i got this error wean changing diff in the F6 menu
[Error  :      SAIN] [SAIN.Helpers.EnumValues] : [[.ctor().TryGetAmmoCaliber().TryParse()]:] : [[Caliber9x18PMM] does not exist in [SAIN.ECaliber] Enum!]
[Error  :      SAIN] [SAIN.Helpers.EnumValues] : [[.ctor().TryGetAmmoCaliber().TryParse()]:] : [[9x18PMM] does not exist in [SAIN.ECaliber] Enum!]

**Comment by minihazel** [comment]
I also get both of these, and

**Comment by Lacyway** [comment]
Fixed with https://github.com/Lacyway/SAIN/commit/fa26b4a5dc51c2324c574924c039a8e8d9ae32e8
