### ISSUE TITLE
Loading into first raid and this error keeps generating in the log console, lags game each time it runs

### ISSUE THREAD

**Issue by Drelok** [Lacyway/SAIN#3]
Posting this so I don't lose the error.   It's some incompatible mod causing it.  Trying to narrow it down to what mod it is, and will update when i figure out which one is doing it.  (adding my mods from one SPT instance this is happening in to the other barebones one at a time to find it)

![image](https://github.com/user-attachments/assets/417f6cb9-cc6e-4eab-9b16-393d2cc2743e)

**Comment by Drelok** [comment]
Welp, guess which mod?   And this can be closed :)   AllZombiesAllDay..

**Comment by Lacyway** [comment]
Fixed
