### ISSUE TITLE
Hideout to Raid issues using action

### ISSUE THREAD

**Issue by TheFunkyNipple** [Lacyway/SAIN#8]
Have no errors that i can see in server or log. Replicaton: Enter Hideout then into raid in quick succession, causes keys to not function.
- no ADS
- no ESC menu
- TESTED: with fresh download and also with our current modpack and issues persisted.
- could heal
- could open SAIN menu

**Comment by VortexDash** [comment]
Can confirm, highly replicable 

1. Launch Server
2. Enter Hideout
3. Load up Raid

- No Esc Button
- No ADS
- if you loot a body direct to you it opens item no search needed
- can view a dog tag on own PMC (No info in tag)

**Comment by Lacyway** [comment]
Resolved with https://github.com/Lacyway/SAIN/commit/284e8806098255311fd802d965a761cfbfbf1f84
